spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost/tiny"
    username: "root"
    password: "123456"

  security:
    oauth2:
      authorizationserver:
        client:
          public-client:
            registration:
              client-id: "public-client"
              client-secret: "$2a$10$h0KujVoYJxn84I0ZecdW0eG9/.HchcWbtC09X1urek64yPZTjI9lO"
              client-authentication-methods:
                - "none"
                - "client_secret_post"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://localhost:5173/oidc-callback"

              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true
