version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
      # MINIO_VOLUMES: /mnt/data
      # MINIO_OPTS: --console-address :9001
    command: server /mnt/data --console-address ":9001"  
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - ./minio/data:/mnt/data
      # - ./minio/conf/config.env:/etc/config.env